server:
  port: 8001
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/proyects
    username: caroatam
    password: 40975241
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    application:
    name: seller-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka